
import Sidebar from "@/components/layout/Sidebar";
import "./globals.css";


export const metadata = {
  title: "portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">

        <section className="max-w-[1320px] mx-auto md:flex bg-[#171b1A]  ">

          <aside  className="w-full md:w-[35%] lg:w-[38.5%]  ">
              <Sidebar/>
          </aside>

           <main className="w-full md:w-[65%] lg:w-[61.5%] min-h-screen">
        {children}

           </main>

        </section>

      </body>
    </html>
  );
}
