
import Sidebar from "@/components/layout/Sidebar";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">

        <section className="max-w-[1320px] mx-auto flex  ">

          <aside  className="w-[508px] min-h-screen   ">
              <Sidebar/>
          </aside>

           <main className="">
        {children}

           </main>

        </section>

      </body>
    </html>
  );
}
